name: Send All Users' Commits

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Get All Users' Commits
        run: |
          COMMITS=$(git log --since="$(date +%Y-%m-%d)T00:00:00Z" --pretty=format:"%h - %an, %s")
          echo "::set-output name=commits::$COMMITS"

      - name: Send Email
        env:
          GMAIL_USERNAME: 'bj.aspire@gmail.com'
          GMAIL_PASSWORD: 'Dang@bj!23'
          RECIPIENT_EMAIL: 'bj.aspire+github@gmail.com'
        run: |
          echo -e "Subject: All Users' Commits\n\n$COMMITS" | msmtp --from=$GMAIL_USERNAME --user=$GMAIL_USERNAME --password=$GMAIL_PASSWORD --host=smtp.gmail.com --port=587 $RECIPIENT_EMAIL
